version: "3.8"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    restart: always
    environment:
      - MONGODB_URI=mongodb://mongo:27017/TicketsDB
    volumes:
      - ./:/app/
      - /app/node_modules
      - /app/.next
    ports:
      - 3000:3000
    depends_on:
      - mongo
    networks:
      - node-webapp-network

  mongo:
    container_name: mongo
    image: mongo
    restart: unless-stopped
    volumes:
      - type: volume
        source: MONGO_DATA
        target: /data/db
      - type: volume
        source: MONGO_CONFIG
        target: /data/configdb
    ports:
      - 27017:27017
    networks:
      - node-webapp-network

networks:
  node-webapp-network:
    driver: bridge

volumes:
  MONGO_DATA:
    name: MONGO_DATA
  MONGO_CONFIG:
    name: MONGO_CONFIG
